//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialsSurveys.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrialsSurveys.App_GlobalResources.ViewResource", typeof(ViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic year.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic year.
        /// </summary>
        public static string AcademicYearFilter {
            get {
                return ResourceManager.GetString("AcademicYearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add application.
        /// </summary>
        public static string AddApplicationButton {
            get {
                return ResourceManager.GetString("AddApplicationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add an application, provide the following information and select Submit..
        /// </summary>
        public static string AddApplicationInstructions {
            get {
                return ResourceManager.GetString("AddApplicationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected a program which requires submission of additional documentation in order for your application to be considered. Click on the document name to view specific details..
        /// </summary>
        public static string AdditionalDocumentsIntroduction {
            get {
                return ResourceManager.GetString("AdditionalDocumentsIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the applicant completed additional education at an English speaking institution?.
        /// </summary>
        public static string AdditionalEducation {
            get {
                return ResourceManager.GetString("AdditionalEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add education.
        /// </summary>
        public static string AddPreviousEducationButton {
            get {
                return ResourceManager.GetString("AddPreviousEducationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddPreviousEducationInstructions {
            get {
                return ResourceManager.GetString("AddPreviousEducationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add program.
        /// </summary>
        public static string AddProgramButton {
            get {
                return ResourceManager.GetString("AddProgramButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted applications.
        /// </summary>
        public static string AdminAppList {
            get {
                return ResourceManager.GetString("AdminAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string AgentFilter {
            get {
                return ResourceManager.GetString("AgentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree with the terms and conditions..
        /// </summary>
        public static string AgreeTermsAndConditions {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected English Language Studies at Georgian and PHPA, Study permit may not get approved.
        /// </summary>
        public static string AlertStudyPermit {
            get {
                return ResourceManager.GetString("AlertStudyPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the applicant completed additional education at an English speaking institution?.
        /// </summary>
        public static string ApplicantCompletedAdditionalEnglish {
            get {
                return ResourceManager.GetString("ApplicantCompletedAdditionalEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant details.
        /// </summary>
        public static string ApplicantDetailsHeading {
            get {
                return ResourceManager.GetString("ApplicantDetailsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant details.
        /// </summary>
        public static string ApplicantDetailsTabHeading {
            get {
                return ResourceManager.GetString("ApplicantDetailsTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant id.
        /// </summary>
        public static string ApplicantId {
            get {
                return ResourceManager.GetString("ApplicantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant is not a duplicate, create a new applicant and application..
        /// </summary>
        public static string ApplicantIsNotDuplicate {
            get {
                return ResourceManager.GetString("ApplicantIsNotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant education.
        /// </summary>
        public static string ApplicantPreviousEducationHeading {
            get {
                return ResourceManager.GetString("ApplicantPreviousEducationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant program choices.
        /// </summary>
        public static string ApplicantProgramChoicesHeading {
            get {
                return ResourceManager.GetString("ApplicantProgramChoicesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        public static string ApplicationCreatedOn {
            get {
                return ResourceManager.GetString("ApplicationCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Date.
        /// </summary>
        public static string ApplicationDate {
            get {
                return ResourceManager.GetString("ApplicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string ApplicationListPage {
            get {
                return ResourceManager.GetString("ApplicationListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Application Form.
        /// </summary>
        public static string ApplicationPageTitle {
            get {
                return ResourceManager.GetString("ApplicationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is complete and is ready to be submitted..
        /// </summary>
        public static string ApplicationReadyToSubmitMsg {
            get {
                return ResourceManager.GetString("ApplicationReadyToSubmitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application status.
        /// </summary>
        public static string ApplicationStatusFilter {
            get {
                return ResourceManager.GetString("ApplicationStatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ApplicationSubmissionStatus {
            get {
                return ResourceManager.GetString("ApplicationSubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yout application has been submitted..
        /// </summary>
        public static string ApplicationSubmittedMsg {
            get {
                return ResourceManager.GetString("ApplicationSubmittedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My application summary.
        /// </summary>
        public static string ApplicationSummaryHeading {
            get {
                return ResourceManager.GetString("ApplicationSummaryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application year.
        /// </summary>
        public static string ApplicationYear {
            get {
                return ResourceManager.GetString("ApplicationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian College International Application System.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of interest.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one additional document attachment is required..
        /// </summary>
        public static string AtleastOneAdditionalDocumentIsRequired {
            get {
                return ResourceManager.GetString("AtleastOneAdditionalDocumentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one program choice is required.
        /// </summary>
        public static string AtleastOneProgramChoiceIsRequired {
            get {
                return ResourceManager.GetString("AtleastOneProgramChoiceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one transcript is required.
        /// </summary>
        public static string AtleastOneTranscriptIsRequired {
            get {
                return ResourceManager.GetString("AtleastOneTranscriptIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSCN.
        /// </summary>
        public static string BSInNursingProgramCode {
            get {
                return ResourceManager.GetString("BSInNursingProgramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificate.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordFormHeading {
            get {
                return ResourceManager.GetString("ChangePasswordFormHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use characters only.
        /// </summary>
        public static string CharactersOnly {
            get {
                return ResourceManager.GetString("CharactersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose program applicant is applying for.
        /// </summary>
        public static string ChooseProgramApplicantIsApplyingFor {
            get {
                return ResourceManager.GetString("ChooseProgramApplicantIsApplyingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selections.
        /// </summary>
        public static string ClearSelections {
            get {
                return ResourceManager.GetString("ClearSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select applicant&apos;s country of birth from the list.
        /// </summary>
        public static string CoBPlaceholder {
            get {
                return ResourceManager.GetString("CoBPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant has completed additional education at an English speaking institution:.
        /// </summary>
        public static string CompletedAdditionalEnglishEducation {
            get {
                return ResourceManager.GetString("CompletedAdditionalEnglishEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant completed their education in an English speaking country:.
        /// </summary>
        public static string CompletedEducationInEglishCountry {
            get {
                return ResourceManager.GetString("CompletedEducationInEglishCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant has completed or is scheduled to complete an English Language test:.
        /// </summary>
        public static string CompletedEnglishTest {
            get {
                return ResourceManager.GetString("CompletedEnglishTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string ContactInformationHeading {
            get {
                return ResourceManager.GetString("ContactInformationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-op.
        /// </summary>
        public static string Coop {
            get {
                return ResourceManager.GetString("Coop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian College.
        /// </summary>
        public static string CopyrightInstitutionName {
            get {
                return ResourceManager.GetString("CopyrightInstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of birth.
        /// </summary>
        public static string CountryOfBirth {
            get {
                return ResourceManager.GetString("CountryOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of citizenship.
        /// </summary>
        public static string CountryOfCitizenship {
            get {
                return ResourceManager.GetString("CountryOfCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new applicant.
        /// </summary>
        public static string CreateApplicantButton {
            get {
                return ResourceManager.GetString("CreateApplicantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new application.
        /// </summary>
        public static string CreateApplicationForApplicant {
            get {
                return ResourceManager.GetString("CreateApplicationForApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user account.
        /// </summary>
        public static string CreateUserAccountButton {
            get {
                return ResourceManager.GetString("CreateUserAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string CrmDocumentCreatedDate {
            get {
                return ResourceManager.GetString("CrmDocumentCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education id.
        /// </summary>
        public static string CrmDocumentEducationId {
            get {
                return ResourceManager.GetString("CrmDocumentEducationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CrmDocumentId {
            get {
                return ResourceManager.GetString("CrmDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string CrmDocumentLocation {
            get {
                return ResourceManager.GetString("CrmDocumentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        public static string CrmDocumentName {
            get {
                return ResourceManager.GetString("CrmDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string CrmDocumentSize {
            get {
                return ResourceManager.GetString("CrmDocumentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CrmDocumentTitle {
            get {
                return ResourceManager.GetString("CrmDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string CrmDocumentType {
            get {
                return ResourceManager.GetString("CrmDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of test.
        /// </summary>
        public static string DateOfTest {
            get {
                return ResourceManager.GetString("DateOfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an agent I declare:
        ///
        ///        That the information contained in this application is true and complete. The information submitted has been reviewed and verified by the applicant.
        ///
        ///        That any false or incomplete information submitted in support of the application may invalidate the application. In such instance Admission offers will be rescinded and this rescission may take place at any time during the application process or enrolment.
        ///
        ///        That I have reviewed the following information with [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        public static string DeleteDocumentButton {
            get {
                return ResourceManager.GetString("DeleteDocumentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of additional information.
        /// </summary>
        public static string DescriptionAdditionalInformation {
            get {
                return ResourceManager.GetString("DescriptionAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string DisclaimerTabHeading {
            get {
                return ResourceManager.GetString("DisclaimerTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter applicant&apos;s date of birth.
        /// </summary>
        public static string DoBPlaceholder {
            get {
                return ResourceManager.GetString("DoBPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document upload.
        /// </summary>
        public static string DocumentUploadHeading {
            get {
                return ResourceManager.GetString("DocumentUploadHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the applicant has completed or is scheduled to take a test, they will be placed in EAPC, pending review of this application.  EAPC is the study of English for post-secondary studies. It represents levels 5-8 (of 8 levels) of our English language program. Students in EAPC already have good English skills..
        /// </summary>
        public static string EAPC_Note {
            get {
                return ResourceManager.GetString("EAPC_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string EducationTabHeading {
            get {
                return ResourceManager.GetString("EducationTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of instruction at Georgian College is English. In addition to the academic admission requirements, all applicants for whom English is not their first language and/or are coming from countries where English is not an official language, must provide proof of language proficiency..
        /// </summary>
        public static string ELP_Note {
            get {
                return ResourceManager.GetString("ELP_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is already in use. Please enter a different email address..
        /// </summary>
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter applicant&apos;s email address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English language proficiency.
        /// </summary>
        public static string EnglishLanguageProficiencyHeading {
            get {
                return ResourceManager.GetString("EnglishLanguageProficiencyHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English language proficiency.
        /// </summary>
        public static string EnglishLanguageProficiencyTabHeading {
            get {
                return ResourceManager.GetString("EnglishLanguageProficiencyTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English language studies.
        /// </summary>
        public static string EnglishLanguageStudies {
            get {
                return ResourceManager.GetString("EnglishLanguageStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English language studies.
        /// </summary>
        public static string EnglishLanguageStudiesHeading {
            get {
                return ResourceManager.GetString("EnglishLanguageStudiesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English language test (i.e., TOEFL, IELTS, CAEL)?.
        /// </summary>
        public static string EnglishLanguageTest {
            get {
                return ResourceManager.GetString("EnglishLanguageTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English language test.
        /// </summary>
        public static string EnglishLanguageTest2 {
            get {
                return ResourceManager.GetString("EnglishLanguageTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A completed English test should have a {0} that occurred in the past..
        /// </summary>
        public static string EnglishTestCompletedDateNotInPast {
            get {
                return ResourceManager.GetString("EnglishTestCompletedDateNotInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English tests have an expiry date. All English tests are valid for two years from the date of the test. {0} should have occurred after {1} and before {2}..
        /// </summary>
        public static string EnglishTestDateOutOfRange {
            get {
                return ResourceManager.GetString("EnglishTestDateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scheduled English test should have a {0} that occurs in the future..
        /// </summary>
        public static string EnglishTestScheduledDateNotInFuture {
            get {
                return ResourceManager.GetString("EnglishTestScheduledDateNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English test transcript uploaded.
        /// </summary>
        public static string EnglishTestUploaded {
            get {
                return ResourceManager.GetString("EnglishTestUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string ErrorFieldIsRequired {
            get {
                return ResourceManager.GetString("ErrorFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find valid program start date for application..
        /// </summary>
        public static string ErrorFinalizeInvalidProgramStartDate {
            get {
                return ResourceManager.GetString("ErrorFinalizeInvalidProgramStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to  Azure queue..
        /// </summary>
        public static string ErrorFinalizeUnableToWriteToQueue {
            get {
                return ResourceManager.GetString("ErrorFinalizeUnableToWriteToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application with specified ID was not found..
        /// </summary>
        public static string ErrorFinalizeUnknownApplicationId {
            get {
                return ResourceManager.GetString("ErrorFinalizeUnknownApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error, try again..
        /// </summary>
        public static string ErrorFinalizeUnknownError {
            get {
                return ResourceManager.GetString("ErrorFinalizeUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the applicant has not completed an English test, they will be placed in ESLG, pending review of this application. ESLG is the study of English as a second language. It represents levels 1-4 (of 8 levels) of our English language program. Students in this level have little to no English skills..
        /// </summary>
        public static string ESLG_Note {
            get {
                return ResourceManager.GetString("ESLG_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This country meets our English Language exemption criteria..
        /// </summary>
        public static string ExemptCountryNote {
            get {
                return ResourceManager.GetString("ExemptCountryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refine by.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By proceeding to the next step you are confirming this application and will not be permitted to make any further changes. Do you wish to lock your application and proceed to payment and submission?.
        /// </summary>
        public static string FinalizeApplication {
            get {
                return ResourceManager.GetString("FinalizeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No - make further changes.
        /// </summary>
        public static string FinalizeApplicationNo {
            get {
                return ResourceManager.GetString("FinalizeApplicationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock application and proceed to next step?.
        /// </summary>
        public static string FinalizeApplicationTitle {
            get {
                return ResourceManager.GetString("FinalizeApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes - proceed.
        /// </summary>
        public static string FinalizeApplicationYes {
            get {
                return ResourceManager.GetString("FinalizeApplicationYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is finalized and a student ID has been requested..
        /// </summary>
        public static string FinalizeSuccess {
            get {
                return ResourceManager.GetString("FinalizeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal information in this application is collected under the legal authority of the Ontario Colleges of Applied Arts and Technology Act, 2002, and in accordance with Sections 38(2) and 41(1) of the Freedom of Information and Protection of Privacy Act (FIPPA), 1990. The information is collected for the purpose of admissions, records management, student service delivery and internal operations at Georgian College. The information is also used for reporting and information sharing with external organiza [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FIPPA_Note {
            get {
                return ResourceManager.GetString("FIPPA_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First choice.
        /// </summary>
        public static string FirstChoice {
            get {
                return ResourceManager.GetString("FirstChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First language/mother tongue.
        /// </summary>
        public static string FirstLanguage {
            get {
                return ResourceManager.GetString("FirstLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name (given name).
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter applicant&apos;s first name.
        /// </summary>
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian college pathway partner.
        /// </summary>
        public static string GeorgianCollegePathwayPartner {
            get {
                return ResourceManager.GetString("GeorgianCollegePathwayPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back To Application And Pay.
        /// </summary>
        public static string GoBackToApplicationAndPay {
            get {
                return ResourceManager.GetString("GoBackToApplicationAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graduate certificate.
        /// </summary>
        public static string GraduateCertificate {
            get {
                return ResourceManager.GetString("GraduateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graduate degree.
        /// </summary>
        public static string GraduateDegree {
            get {
                return ResourceManager.GetString("GraduateDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the applicant completed any English tests? (i.e., TOEFL, IELTS, CAEL).
        /// </summary>
        public static string HasApplicantCompletedEnglishTests {
            get {
                return ResourceManager.GetString("HasApplicantCompletedEnglishTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the applicant completed any English test?.
        /// </summary>
        public static string HasTheApplicantCompletedAnyEnglishTest {
            get {
                return ResourceManager.GetString("HasTheApplicantCompletedAnyEnglishTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the applicant graduated?.
        /// </summary>
        public static string HasTheApplicantGraduated {
            get {
                return ResourceManager.GetString("HasTheApplicantGraduated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the following options to indicate how the applicant will meet Georgian’s English language proficiency requirements..
        /// </summary>
        public static string HowApplicantWillMeetEnglishProficiency {
            get {
                return ResourceManager.GetString("HowApplicantWillMeetEnglishProficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate which program(s) the applicant wishes to apply for (select at least one option).
        /// </summary>
        public static string IndicateProgramsMessage {
            get {
                return ResourceManager.GetString("IndicateProgramsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indicates required field.
        /// </summary>
        public static string IndicatesRequiredField {
            get {
                return ResourceManager.GetString("IndicatesRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoPageTitle {
            get {
                return ResourceManager.GetString("InfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form is complete.
        /// </summary>
        public static string InformationComplete {
            get {
                return ResourceManager.GetString("InformationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is missing information on the form.
        /// </summary>
        public static string InformationMissing {
            get {
                return ResourceManager.GetString("InformationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not accept applications for applicants younger than {0} years old. &apos;{1}&apos; should occur on or before {2}.
        /// </summary>
        public static string InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid email address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the student scheduled to complete a test?.
        /// </summary>
        public static string IsStudentScheduledToCompleteTest {
            get {
                return ResourceManager.GetString("IsStudentScheduledToCompleteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name (family name).
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter applicant&apos;s last name.
        /// </summary>
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level code.
        /// </summary>
        public static string LevelCode {
            get {
                return ResourceManager.GetString("LevelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginEmailAddress {
            get {
                return ResourceManager.GetString("LoginEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to georgian_canada_logo.svg.
        /// </summary>
        public static string LoginLogoFileName {
            get {
                return ResourceManager.GetString("LoginLogoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing address.
        /// </summary>
        public static string MailingAddressHeading {
            get {
                return ResourceManager.GetString("MailingAddressHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing address line 1.
        /// </summary>
        public static string MailingAddressLine1 {
            get {
                return ResourceManager.GetString("MailingAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing address line 2.
        /// </summary>
        public static string MailingAddressLine2 {
            get {
                return ResourceManager.GetString("MailingAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing address is the same as permanent address.
        /// </summary>
        public static string MailingAddressSameAsPermanent {
            get {
                return ResourceManager.GetString("MailingAddressSameAsPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageExternalLoginsHeading {
            get {
                return ResourceManager.GetString("ManageExternalLoginsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of test.
        /// </summary>
        public static string NameOfTest {
            get {
                return ResourceManager.GetString("NameOfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Test.
        /// </summary>
        public static string NameOfTestId {
            get {
                return ResourceManager.GetString("NameOfTestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string NavigationApplication {
            get {
                return ResourceManager.GetString("NavigationApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavigationHomePage {
            get {
                return ResourceManager.GetString("NavigationHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profile.
        /// </summary>
        public static string NavigationManageProfile {
            get {
                return ResourceManager.GetString("NavigationManageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have a local account..
        /// </summary>
        public static string NoLocalAccountMessage {
            get {
                return ResourceManager.GetString("NoLocalAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This country does not meet our English language exemption criteria.  Please select another option below.
        /// </summary>
        public static string NonExemptCountryNote {
            get {
                return ResourceManager.GetString("NonExemptCountryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application no..
        /// </summary>
        public static string OcasNumber {
            get {
                return ResourceManager.GetString("OcasNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer status.
        /// </summary>
        public static string OfferStatus {
            get {
                return ResourceManager.GetString("OfferStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer status.
        /// </summary>
        public static string OfferStatusFilter {
            get {
                return ResourceManager.GetString("OfferStatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the applicant has only one name, please enter it in both the first and last name fields..
        /// </summary>
        public static string OneNameMessage {
            get {
                return ResourceManager.GetString("OneNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year post-secondary in English.
        /// </summary>
        public static string OneYearPostSecondaryInEnglish {
            get {
                return ResourceManager.GetString("OneYearPostSecondaryInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario secondary school diploma.
        /// </summary>
        public static string OntarioSecondarySchoolDiploma {
            get {
                return ResourceManager.GetString("OntarioSecondarySchoolDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing application.
        /// </summary>
        public static string OpenExistingApplicationButton {
            get {
                return ResourceManager.GetString("OpenExistingApplicationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other information.
        /// </summary>
        public static string OtherInformationHeading {
            get {
                return ResourceManager.GetString("OtherInformationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the applicant has a current passport, please upload a copy of the picture page. This will assist admissions with validating personal details..
        /// </summary>
        public static string PassportFirstPageUploadMessage {
            get {
                return ResourceManager.GetString("PassportFirstPageUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport uploaded.
        /// </summary>
        public static string PassportUploaded {
            get {
                return ResourceManager.GetString("PassportUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay fee using TouchNet.
        /// </summary>
        public static string PaymentButton {
            get {
                return ResourceManager.GetString("PaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment has been cancelled.  This application has not been submitted. 
        /// 
        ///You may return to this application at any time to view, edit or submit it..
        /// </summary>
        public static string PaymentCancelMsg {
            get {
                return ResourceManager.GetString("PaymentCancelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing error.  Your payment has not been processed and this application has not been submitted.   Please review the payment information you entered and try again or return to this application at a later date.  If you continue to experience issues submitting this application please contact reginternational@georgiancollege.ca..
        /// </summary>
        public static string PaymentErrorMsg {
            get {
                return ResourceManager.GetString("PaymentErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix all errors on the application before proceeding to this step..
        /// </summary>
        public static string PaymentFinalizeWarning {
            get {
                return ResourceManager.GetString("PaymentFinalizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Errors Before Proceeding.
        /// </summary>
        public static string PaymentFinalizeWarningTitle {
            get {
                return ResourceManager.GetString("PaymentFinalizeWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for completing this application. In order to submit the application for processing you must pay an application fee of {0}.
        ///
        ///Once you submit this application, we will review it in detail and contact you with further instructions. You may return to this application at any time to view it. To make changes to the application or to provide additional/final documents, please contact reginternational@georgiancollege.ca
        ///
        ///If you have any questions, please contact your Regional Manager or In Country Rep [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentNeeded {
            get {
                return ResourceManager.GetString("PaymentNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system must generate a student ID before payment can be processed. Please wait for a student ID to be generated..
        /// </summary>
        public static string PaymentNeedStudentId {
            get {
                return ResourceManager.GetString("PaymentNeedStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment has been successfully applied and this application has been submitted. 
        /// 
        ///You may return to this application at any time to view it. To make changes to the application or to provide additional/final documents, please contact reginternational@georgiancollege.ca.
        /// </summary>
        public static string PaymentSuccessMsg {
            get {
                return ResourceManager.GetString("PaymentSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PaymentTabHeading {
            get {
                return ResourceManager.GetString("PaymentTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string PaymentTitle {
            get {
                return ResourceManager.GetString("PaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for completing this application. We value your business and have waived your application fee.
        ///
        ///Once you submit this application, we will review it in detail and contact you with further instructions. You may return to this application at any time to view it. To make changes to the application or to provide additional/final documents, please contact reginternational@georgiancollege.ca
        ///
        ///If you have any questions, please contact your Regional Manager or In Country Representative. Thank you for do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentWaived {
            get {
                return ResourceManager.GetString("PaymentWaived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Waived.
        /// </summary>
        public static string PaymentWaivedTitle {
            get {
                return ResourceManager.GetString("PaymentWaivedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent address.
        /// </summary>
        public static string PermanentAddressHeading {
            get {
                return ResourceManager.GetString("PermanentAddressHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent address line 1.
        /// </summary>
        public static string PermanentAddressLine1 {
            get {
                return ResourceManager.GetString("PermanentAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent address line 2.
        /// </summary>
        public static string PermanentAddressLine2 {
            get {
                return ResourceManager.GetString("PermanentAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address on the letter of acceptance will be the permanent address.
        /// </summary>
        public static string PermanentAddressMessage {
            get {
                return ResourceManager.GetString("PermanentAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: First, middle and last name must be as it appears on passport. &lt;br/&gt;If the applicant has only one name, please enter it in both the first and last name fields..
        /// </summary>
        public static string PersonalDetails_Note {
            get {
                return ResourceManager.GetString("PersonalDetails_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string PersonalInformationHeading {
            get {
                return ResourceManager.GetString("PersonalInformationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal/zip code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post-secondary.
        /// </summary>
        public static string PostSecondary {
            get {
                return ResourceManager.GetString("PostSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-secondary program (certificate, diploma, degree).
        /// </summary>
        public static string PostSecondaryProgram {
            get {
                return ResourceManager.GetString("PostSecondaryProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Secondary Program(certificate, diploma, degree).
        /// </summary>
        public static string PostSecondaryProgramHeading {
            get {
                return ResourceManager.GetString("PostSecondaryProgramHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred name.
        /// </summary>
        public static string PreferredName {
            get {
                return ResourceManager.GetString("PreferredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred start date.
        /// </summary>
        public static string PreferredStartDate {
            get {
                return ResourceManager.GetString("PreferredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHPA.
        /// </summary>
        public static string PreHealthSciencesProgramCode {
            get {
                return ResourceManager.GetString("PreHealthSciencesProgramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential type.
        /// </summary>
        public static string PreviousEducationCredentialType {
            get {
                return ResourceManager.GetString("PreviousEducationCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type id.
        /// </summary>
        public static string PreviousEducationCredentialTypeId {
            get {
                return ResourceManager.GetString("PreviousEducationCredentialTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcripts.
        /// </summary>
        public static string PreviousEducationDocument {
            get {
                return ResourceManager.GetString("PreviousEducationDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Education Transcripts.
        /// </summary>
        public static string PreviousEducationDocumentList {
            get {
                return ResourceManager.GetString("PreviousEducationDocumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous education for {0}.
        /// </summary>
        public static string PreviousEducationEntityName {
            get {
                return ResourceManager.GetString("PreviousEducationEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following errors before saving:.
        /// </summary>
        public static string PreviousEducationErrors {
            get {
                return ResourceManager.GetString("PreviousEducationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string PreviousEducationGraduatedNo {
            get {
                return ResourceManager.GetString("PreviousEducationGraduatedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PreviousEducationGraduatedYes {
            get {
                return ResourceManager.GetString("PreviousEducationGraduatedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PreviousEducationId {
            get {
                return ResourceManager.GetString("PreviousEducationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of educational institution.
        /// </summary>
        public static string PreviousEducationName {
            get {
                return ResourceManager.GetString("PreviousEducationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please list all educational institutions you have attended or are currently attending, in chronological order. List high schools (secondary) and any colleges or universities (post-secondary), and whether you graduated. As a matter of academic honesty it is very important to list all of your education, as it will ensure that your application is assessed properly. Also, if you decide to apply for transfer credits, only accredited institutions that appear on your admission application will be considered. Below [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PreviousEducationNote {
            get {
                return ResourceManager.GetString("PreviousEducationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.georgiancollege.ca/privacy-policy/.
        /// </summary>
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Additional Documents Requirement.
        /// </summary>
        public static string ProgramAdditionalDocumentsRequirement {
            get {
                return ResourceManager.GetString("ProgramAdditionalDocumentsRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string ProgramCampus {
            get {
                return ResourceManager.GetString("ProgramCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The college does not guarantee the availability of programs. Please select up to three programs and rank them in order of preference. Choice number 1 will be the program reviewed first. You may change the order of choices by dragging and dropping..
        /// </summary>
        public static string ProgramChoices_Note {
            get {
                return ResourceManager.GetString("ProgramChoices_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program count.
        /// </summary>
        public static string ProgramChoicesCount {
            get {
                return ResourceManager.GetString("ProgramChoicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program choice.
        /// </summary>
        public static string ProgramChoiceTabHeading {
            get {
                return ResourceManager.GetString("ProgramChoiceTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program code.
        /// </summary>
        public static string ProgramCode {
            get {
                return ResourceManager.GetString("ProgramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential type.
        /// </summary>
        public static string ProgramCredentialType {
            get {
                return ResourceManager.GetString("ProgramCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program/Degree.
        /// </summary>
        public static string ProgramDegree {
            get {
                return ResourceManager.GetString("ProgramDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string ProgramEndDate {
            get {
                return ResourceManager.GetString("ProgramEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ProgramId {
            get {
                return ResourceManager.GetString("ProgramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program list.
        /// </summary>
        public static string ProgramListHeading {
            get {
                return ResourceManager.GetString("ProgramListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search criteria.
        /// </summary>
        public static string ProgramListSearchCriteriaHeading {
            get {
                return ResourceManager.GetString("ProgramListSearchCriteriaHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program offering.
        /// </summary>
        public static string ProgramOffering {
            get {
                return ResourceManager.GetString("ProgramOffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        public static string ProgramOrder {
            get {
                return ResourceManager.GetString("ProgramOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string ProgramStartDate {
            get {
                return ResourceManager.GetString("ProgramStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start term.
        /// </summary>
        public static string ProgramStartTerm {
            get {
                return ResourceManager.GetString("ProgramStartTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/state.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string RegisterConfirmEmail {
            get {
                return ResourceManager.GetString("RegisterConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email and confirmation email do not match..
        /// </summary>
        public static string RegisterEmailNoMatchError {
            get {
                return ResourceManager.GetString("RegisterEmailNoMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string RegisterPasswordTooShortError {
            get {
                return ResourceManager.GetString("RegisterPasswordTooShortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        public static string RemoveLoginProviderMessage {
            get {
                return ResourceManager.GetString("RemoveLoginProviderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Home Screen .
        /// </summary>
        public static string ReturnToHomeScreen {
            get {
                return ResourceManager.GetString("ReturnToHomeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string SaveAndCloseButton {
            get {
                return ResourceManager.GetString("SaveAndCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save freedom of information.
        /// </summary>
        public static string SaveFreedomOfInformationButton {
            get {
                return ResourceManager.GetString("SaveFreedomOfInformationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second choice.
        /// </summary>
        public static string SecondChoice {
            get {
                return ResourceManager.GetString("SecondChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SetPasswordButton {
            get {
                return ResourceManager.GetString("SetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipButton {
            get {
                return ResourceManager.GetString("SkipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant email address.
        /// </summary>
        public static string StudentEmailAddress {
            get {
                return ResourceManager.GetString("StudentEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student id.
        /// </summary>
        public static string StudentId {
            get {
                return ResourceManager.GetString("StudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SubmissionStatus {
            get {
                return ResourceManager.GetString("SubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermsAndConditionsHeading {
            get {
                return ResourceManager.GetString("TermsAndConditionsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall test score.
        /// </summary>
        public static string TestScore {
            get {
                return ResourceManager.GetString("TestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third choice.
        /// </summary>
        public static string ThirdChoice {
            get {
                return ResourceManager.GetString("ThirdChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that this is a test site only. Applications submitted will not be processed..
        /// </summary>
        public static string ThisIsATest {
            get {
                return ResourceManager.GetString("ThisIsATest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three years study in English.
        /// </summary>
        public static string ThreeYearsStudyInEnglish {
            get {
                return ResourceManager.GetString("ThreeYearsStudyInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian College Canada logo.
        /// </summary>
        public static string TopNavbarLogoDescription {
            get {
                return ResourceManager.GetString("TopNavbarLogoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to georgian_logo-green_white.svg.
        /// </summary>
        public static string TopNavbarLogoFileName {
            get {
                return ResourceManager.GetString("TopNavbarLogoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undergraduate degree.
        /// </summary>
        public static string UndergraduateDegree {
            get {
                return ResourceManager.GetString("UndergraduateDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload date.
        /// </summary>
        public static string UploadDate {
            get {
                return ResourceManager.GetString("UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload document.
        /// </summary>
        public static string UploadDocumentButton {
            get {
                return ResourceManager.GetString("UploadDocumentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload English test.
        /// </summary>
        public static string UploadEnglishTest {
            get {
                return ResourceManager.GetString("UploadEnglishTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload passport.
        /// </summary>
        public static string UploadPassport {
            get {
                return ResourceManager.GetString("UploadPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload transcripts.
        /// </summary>
        public static string UploadTranscripts {
            get {
                return ResourceManager.GetString("UploadTranscripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string UserInfoFirstName {
            get {
                return ResourceManager.GetString("UserInfoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string UserInfoLastName {
            get {
                return ResourceManager.GetString("UserInfoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserInfoUserName {
            get {
                return ResourceManager.GetString("UserInfoUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetting.
        /// </summary>
        public static string VettingPage {
            get {
                return ResourceManager.GetString("VettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which country did the applicant complete their education?.
        /// </summary>
        public static string WhichCountryCompletedEducation {
            get {
                return ResourceManager.GetString("WhichCountryCompletedEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate which program(s) the applicant wishes to apply for (select at least one option).
        /// </summary>
        public static string WhichProgramsApplyFor {
            get {
                return ResourceManager.GetString("WhichProgramsApplyFor", resourceCulture);
            }
        }
    }
}
